language: cpp
compiler:
    - gcc
    - clang
git:
    submodules: false

before_install:
    - "sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test"
    - "sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa"
    - "sudo apt-get update -qq"
    - "sudo apt-get install -qq libboost-dev libboost-test-dev libboost-program-options-dev cmake clang qt5-default libqt5webkit5"
    - "sudo apt-get update; sudo apt-get install gcc-4.8 g++-4.8"
    - "sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20"
    - "sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20"
    - "sudo update-alternatives --config gcc"
    - "sudo update-alternatives --config g++"
    - "gcc --version"
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

    
script: mkdir build && cd build && cmake ../ && make -j